import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { Framework, MockScoreData } from '../types';
import { controlsByFrameworkId } from '../data/controls';
import { getProductById } from '../data/manageEngineProducts';

const addHeaderFooter = (doc: jsPDF, frameworkName: string) => {
  const pageCount = doc.getNumberOfPages();
  const date = new Date().toLocaleDateString();

  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(37, 99, 235);
    doc.text(`ComplianceIQ Report — ${frameworkName}`, 14, 10);
    doc.text(`Page ${i}`, 185, 10, { align: 'right' });

    doc.setTextColor(100);
    doc.setFontSize(8);
    doc.text(`Generated ${date} · Confidential`, 14, 290);
    doc.text('For internal compliance planning only.', 185, 290, { align: 'right' });
  }
};

const addCoverPage = (doc: jsPDF, framework: Framework, scoreData: MockScoreData) => {
  const assessmentDate = new Date().toLocaleDateString();
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.text('ComplianceIQ', 14, 24);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.text('Compliance Assessment Report', 14, 60);
  doc.setFontSize(12);
  doc.text('Organization: Your Organization', 14, 75);
  doc.text(`Framework: ${framework.fullName}`, 14, 85);
  doc.text(`Assessment Date: ${assessmentDate}`, 14, 95);
  doc.text(`Overall Score: ${scoreData.overallScore}%`, 14, 105);

  doc.setFontSize(13);
  doc.setTextColor(37, 99, 235);
  doc.text('Generated by ComplianceIQ', 14, 120);
};

const captureChartImage = async (selector: string) => {
  const element = document.querySelector(selector) as HTMLElement | null;
  if (!element) return null;
  const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#ffffff' });
  return canvas.toDataURL('image/png');
};

export const exportExecutivePdf = async (framework: Framework, scoreData: MockScoreData) => {
  const doc = new jsPDF();
  addCoverPage(doc, framework, scoreData);

  doc.addPage();
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text('Score Summary', 14, 20);
  doc.setFontSize(12);
  doc.text(`Overall Score: ${scoreData.overallScore}%`, 14, 30);
  doc.text(`Maturity Tier: ${scoreData.overallScore >= 81 ? 'Optimized' : scoreData.overallScore >= 66 ? 'Managed' : scoreData.overallScore >= 41 ? 'Developing' : 'Initial'}`, 14, 38);

  autoTable(doc, {
    startY: 46,
    head: [['Family', 'Score', 'Controls']],
    body: scoreData.familyScores.map((row) => [row.family, `${row.score}%`, String(row.controlCount)]),
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  autoTable(doc, {
    startY: (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY
      ? (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable!.finalY + 8
      : 150,
    head: [['Passed', 'Failed', 'Partial', 'N/A']],
    body: [[scoreData.passed, scoreData.failed, scoreData.partial, scoreData.notApplicable]],
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  const trendImage = await captureChartImage('#trend-chart');
  if (trendImage) {
    doc.addImage(trendImage, 'PNG', 14, 180, 180, 70);
  }

  doc.addPage();
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text('Top Remediation Actions', 14, 20);

  autoTable(doc, {
    startY: 28,
    head: [['#', 'Control ID', 'Action', 'Recommended Product', 'Est. Gain']],
    body: scoreData.remediationActions.slice(0, 5).map((action, index) => [
      String(index + 1),
      action.controlId,
      action.actionDescription,
      action.recommendedProduct,
      `${action.scoreGain}%`,
    ]),
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 2 },
  });

  addHeaderFooter(doc, framework.name);
  doc.save(`ComplianceIQ-Executive-${framework.id}.pdf`);
};

export const exportAuditorPdf = async (framework: Framework, scoreData: MockScoreData) => {
  const doc = new jsPDF();
  addCoverPage(doc, framework, scoreData);

  doc.addPage();
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text('Framework Overview', 14, 20);
  doc.setFontSize(11);
  doc.text(framework.description, 14, 30, { maxWidth: 180 });

  autoTable(doc, {
    startY: 42,
    head: [['Metric', 'Value']],
    body: [
      ['Framework', framework.fullName],
      ['Region', framework.region.join(', ')],
      ['Controls', String(framework.controlCount)],
      ['ME Coverage', `${framework.meCoveragePercent}%`],
      ['Overall Score', `${scoreData.overallScore}%`],
    ],
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  const controls = controlsByFrameworkId[framework.id] ?? [];
  doc.addPage();
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text('Control-by-Control Evidence Table', 14, 20);

  autoTable(doc, {
    startY: 26,
    head: [['Control ID', 'Title', 'Family', 'Status', 'Weight', 'ME Product', 'Coverage']],
    body: controls.map((control) => {
      const primary = control.manageEngineProducts.find((mapping) => mapping.primary) ?? control.manageEngineProducts[0];
      const product = primary ? getProductById(primary.productId)?.shortName ?? primary.productId : '—';
      return [
        control.id,
        control.title,
        control.family,
        'Partial',
        String(control.weight),
        product,
        primary ? `${primary.coverage}%` : '—',
      ];
    }),
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 8, cellPadding: 2 },
  });

  doc.addPage();
  doc.setFontSize(16);
  doc.text('Methodology', 14, 20);
  doc.setFontSize(11);
  doc.text(
    'Scoring formula: control score = (passed checks × weight) / (total checks × weight) × 100.\\nFamily score is weighted average of control scores.\\nFramework score is weighted average of family scores.',
    14,
    32,
    { maxWidth: 180 }
  );

  doc.addPage();
  doc.setFontSize(16);
  doc.text('Disclaimer', 14, 20);
  doc.setFontSize(11);
  doc.text(
    'This report is generated from demonstration data and is intended for informational planning purposes only. It is not legal advice, certification, or a substitute for an independent audit. Organizations remain responsible for validating compliance obligations with qualified legal and security professionals.',
    14,
    32,
    { maxWidth: 180 }
  );

  addHeaderFooter(doc, framework.name);
  doc.save(`ComplianceIQ-Auditor-${framework.id}.pdf`);
};
